project:
  type: website
  output-dir: docs
  
website:
  title: "Project 1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Viz"
        menu: 
          - text: "Valentine's Day"
            href: valentines_day.qmd
          - text: "Holiday Travel"
            href: holiday_travel.qmd
          
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

