project:
  type: website
  output-dir: docs
  
website:
  title: "DS 2 Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Viz"
        menu: 
          - text: "Valentine's Day"
            href: valentines_day.qmd
          - text: "Holiday Travel"
            href: holiday_travel.qmd
          - text: "Netflix Analysis"
            href: string_analysis.qmd
          - text: "Simulation Study"
            href: simulation_study.qmd
      - text: "Amazon Ethical Analysis"
        href: ethics.qmd
 

format:
  html:
    code-tools:
      source: true
      toggle: false
      caption: none   
    code-fold: true
    code-summary: "Show the code"      
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

editor: visual

